# Generated by Django 4.2.11 on 2024-04-12 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='test_user',
        ),
    ]
